name: Update DockerHub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@93b93397c27ed52b4055b8c6b2f8d92456ab3c56 # v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wildwildangel/sqlmap
          short-description: Alpine-based image to run sqlmap
